# Generated by Django 2.2.1 on 2020-03-02 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cargo', models.CharField(choices=[('Ingeniero Preventa', 'Ingeniero Preventa'), ('Coordinador Preventa', 'Coordinador Preventa'), ('Operador SET', 'Operador SET'), ('Operador GTI', 'Operador GTI'), ('Arquitecto Cloud', 'Arquitecto Cloud'), ('Ingeniero Especialista', 'Ingeniero Especialista'), ('Agente de mesa', 'Agente de mesa'), ('Gerente de proyecto', 'Gerente de proyecto'), ('Contador', 'Contador'), ('Analista ITIL', 'Analista ITIL'), ('Ingeniero implementacion', 'Ingeniero implementacion'), ('Lider de implementacion', 'Lider de implementacion'), ('Lider NOC', 'Lider NOC'), ('Lider SOC', 'Lider SOC')], default='Ingeniero Preventa', max_length=30)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('tipo_proy', models.CharField(choices=[('GTI', 'GTI'), ('SET', 'SET'), ('CLOUD', 'CLOUD')], default='GTI', max_length=7)),
                ('fecha_kick', models.DateField()),
                ('fecha_inicio', models.DateField()),
                ('moneda', models.CharField(choices=[('COP', 'COP'), ('USD', 'USD')], default='COP', max_length=7)),
                ('trm', models.IntegerField()),
                ('costo_implementacion', models.IntegerField()),
                ('margen', models.IntegerField()),
                ('ans', models.CharField(choices=[('95', '95'), ('97', '97'), ('99', '99')], default='95', max_length=7)),
                ('incremento', models.CharField(choices=[('IPC', 'IPC'), ('SLMV', 'SLMV')], default='IPC', max_length=7)),
                ('costo_imp_diferido', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=7)),
                ('facturacion', models.CharField(choices=[('Mes Vencido', 'Mes Vencido'), ('Mes Corriente', 'Mes Corriente')], default='MES_VENCIDO', max_length=13)),
                ('penal', models.IntegerField()),
                ('duracion_total', models.IntegerField()),
                ('duracion_implementacion', models.IntegerField()),
                ('costo_mensual', models.IntegerField()),
                ('cotizador', models.FileField(blank=True, upload_to='media/')),
                ('documento', models.FileField(blank=True, upload_to='media/')),
                ('vista', models.BooleanField(null=True)),
                ('participantes', models.ManyToManyField(related_name='participantes', to='home.Usuario')),
            ],
        ),
    ]
