# Generated by Django 2.2.1 on 2020-03-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='trm',
            field=models.FloatField(),
        ),
    ]
