# Generated by Django 2.2.1 on 2020-03-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200305_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='trm',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
