# Generated by Django 2.2.1 on 2020-03-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200305_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='trm',
            field=models.IntegerField(),
        ),
    ]
