# Generated by Django 2.2.1 on 2020-03-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_tarea_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('En proceso', 'En proceso'), ('Finalizada', 'Finalizada')], default='PROCESO', max_length=10, null=True),
        ),
    ]
