# Generated by Django 2.2.1 on 2020-03-09 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_usuario_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='imagen',
        ),
    ]
